"""Frozen raw-feature names and intraday timing definitions."""

from __future__ import annotations

M30_SLOTS = (
    (930, 1000),
    (1001, 1030),
    (1031, 1100),
    (1101, 1130),
    (1301, 1330),
    (1331, 1400),
    (1401, 1430),
    (1431, 1500),
)

M30_FIELDS = (
    "OPEN",
    "CLOSE",
    "HIGH",
    "LOW",
    "VWAP",
    "VOLUME_FIRST",
    "VOLUME_LAST",
    "VOLUME_MEAN",
    "AMOUNT_FIRST",
    "AMOUNT_LAST",
    "AMOUNT_MEAN",
    "VOL_SHARE",
    "AMT_SHARE",
    "RET_OC",
    "RET_CC",
    "GAP",
    "RET_VWAP",
    "RANGE_OPEN",
    "BODY",
    "ABS_BODY",
    "UPPER_SHADOW",
    "LOWER_SHADOW",
    "BODY_RANGE_RATIO",
    "CLOSE_POS",
    "VWAP_POS",
    "CLOSE_VWAP",
    "OPEN_VWAP",
    "HIGH_VWAP",
    "LOW_VWAP",
    "VWAP_OPEN",
    "VOL_CHG",
    "AMT_CHG",
    "UP_VOL_RATIO",
    "DOWN_VOL_RATIO",
    "NET_UP_VOL_RATIO",
    "UP_AMT_RATIO",
    "DOWN_AMT_RATIO",
    "NET_UP_AMT_RATIO",
    "RET_PER_AMT",
    "RET_PER_VOL",
    "ABS_RET_PER_AMT",
    "ABS_RET_PER_VOL",
    "RANGE_PER_AMT",
    "RANGE_PER_VOL",
    "MIN_RET_STD",
    "REALIZED_VOL",
    "ABS_MIN_RET_MEAN",
    "MAX_MIN_RET",
    "MIN_MIN_RET",
    "UP_MIN_RATIO",
    "DOWN_MIN_RATIO",
    "FLAT_MIN_RATIO",
    "CUM_RET",
    "CUM_VWAP",
    "CLOSE_CUM_VWAP",
    "CUM_CLOSE_POS",
    "DIST_TO_CUM_HIGH",
    "DIST_TO_CUM_LOW",
    "PRICE_DEV_VWAP_MEAN",
    "PRICE_DEV_VWAP_ABS_MEAN",
    "PRICE_DEV_VWAP_STD",
    "PRICE_MAX_DEV_OPEN",
    "PRICE_MIN_DEV_OPEN",
    "PRICE_DEV_RANGE_OPEN",
    "RET_VOL_CORR",
    "RET_AMT_CORR",
    "ABSRET_VOL_CORR",
    "ABSRET_AMT_CORR",
    "PRICEDEV_VOL_CORR",
    "PRICEDEV_AMT_CORR",
)

D1_FIELDS = (
    "OPEN_REL_CLOSE",
    "HIGH_REL_CLOSE",
    "LOW_REL_CLOSE",
    "VWAP_REL_CLOSE",
    "RANGE_OPEN",
    "BODY",
    "ABS_BODY",
    "UPPER_SHADOW",
    "LOWER_SHADOW",
    "BODY_RANGE_RATIO",
    "CLOSE_POS",
    "VWAP_POS",
    "RET_OC",
    "RET_CC_1D",
    "GAP",
    "RET_VWAP_1D",
    "CLOSE_VWAP",
    "OPEN_VWAP",
    "LOG_VOLUME",
    "LOG_AMOUNT",
    "VOL_CHG_1D",
    "AMT_CHG_1D",
    "VWAP_AMOUNT_INTENSITY",
    "RET_PER_AMOUNT",
    "RANGE_PER_AMOUNT",
    "RET_5D",
    "RET_10D",
    "RET_20D",
    "RET_60D",
    "REV_1D",
    "MA_DEV_5D",
    "MA_DEV_20D",
    "MA_DEV_60D",
    "CLOSE_POS_20D",
    "CLOSE_POS_60D",
    "DIST_HIGH_20D",
    "DIST_LOW_20D",
    "DIST_HIGH_60D",
    "DIST_LOW_60D",
)

EO_FIELDS = (
    "OPEN",
    "CLOSE",
    "HIGH",
    "LOW",
    "VWAP",
    "RET_PREV_CLOSE",
    "VWAP_PREV_CLOSE",
    "AUCTION_RET_PREV_CLOSE",
    "VOLUME_FIRST",
    "VOLUME_LAST",
    "VOLUME_MEAN",
    "AMOUNT_FIRST",
    "AMOUNT_LAST",
    "AMOUNT_MEAN",
    "VOL_SHARE_PREV_DAY",
    "AMT_SHARE_PREV_DAY",
    "RET_OC",
    "RANGE_OPEN",
    "BODY",
    "ABS_BODY",
    "UPPER_SHADOW",
    "LOWER_SHADOW",
    "BODY_RANGE_RATIO",
    "CLOSE_POS",
    "VWAP_POS",
    "CLOSE_VWAP",
    "OPEN_VWAP",
    "HIGH_VWAP",
    "LOW_VWAP",
    "VWAP_OPEN",
    "UP_VOL_RATIO",
    "DOWN_VOL_RATIO",
    "NET_UP_VOL_RATIO",
    "UP_AMT_RATIO",
    "DOWN_AMT_RATIO",
    "NET_UP_AMT_RATIO",
    "REALIZED_VOL",
    "ABS_MIN_RET_MEAN",
    "MAX_MIN_RET",
    "MIN_MIN_RET",
    "UP_MIN_RATIO",
    "DOWN_MIN_RATIO",
    "FLAT_MIN_RATIO",
    "PRICE_DEV_VWAP_MEAN",
    "PRICE_DEV_VWAP_ABS_MEAN",
    "PRICE_DEV_VWAP_STD",
    "PRICE_MAX_DEV_OPEN",
    "PRICE_MIN_DEV_OPEN",
    "PRICE_DEV_RANGE_OPEN",
    "RET_VOL_CORR",
    "RET_AMT_CORR",
    "ABSRET_VOL_CORR",
    "ABSRET_AMT_CORR",
    "PRICEDEV_VOL_CORR",
    "PRICEDEV_AMT_CORR",
    "AUCTION_VOL_SHARE",
    "AUCTION_AMT_SHARE",
    "AUCTION_PRICE_DEV_VWAP",
)

M30_FEATURE_COLUMNS = tuple(f"M30_{field}_{slot}" for field in M30_FIELDS for slot in range(1, 9))
D1_FEATURE_COLUMNS = tuple(f"D1_{field}" for field in D1_FIELDS)
EO_FEATURE_COLUMNS = tuple(f"EO_{field}" for field in EO_FIELDS)
O2O_RAW_FEATURE_COLUMNS = M30_FEATURE_COLUMNS + D1_FEATURE_COLUMNS
DE_RAW_FEATURE_COLUMNS = O2O_RAW_FEATURE_COLUMNS + EO_FEATURE_COLUMNS

assert len(M30_FIELDS) == 70
assert len(M30_FEATURE_COLUMNS) == 560
assert len(D1_FEATURE_COLUMNS) == 39
assert len(EO_FEATURE_COLUMNS) == 58
assert len(O2O_RAW_FEATURE_COLUMNS) == 599
assert len(DE_RAW_FEATURE_COLUMNS) == 657
